apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    run: maliev-authservice-api
  name: maliev-authservice-api
  namespace: maliev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    run: maliev-authservice-api
  sessionAffinity: None
  type: NodePort
