name: CI - Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Maliev.AuthService.sln
      working-directory: ${{ github.workspace }}

    - name: Build
      run: dotnet build Maliev.AuthService.sln --no-restore

    - name: Test
      run: dotnet test Maliev.AuthService.sln --no-build --verbosity normal

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: maliev-website

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-authservice:${{ github.sha }} -f Maliev.AuthService.Api/Dockerfile .
        docker push asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-dev/maliev-authservice:${{ github.sha }}

    - name: Checkout maliev-gitops repository
      uses: actions/checkout@v3
      with:
        repository: MALIEV-Co-Ltd/maliev-gitops
        token: ${{ secrets.GITOPS_PAT }}
        path: maliev-gitops

    - name: Update targetRevision in maliev-gitops
      run: |
        sed -i "s/targetRevision: .*/targetRevision: ${{ github.sha }}/" maliev-gitops/argocd/environments/dev/apps/auth-service.yaml
        
    - name: Commit and push changes
      run: |
        cd maliev-gitops
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update targetRevision for auth-service to ${{ github.sha }}"
        git push