name: CI - Main

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: auth-service-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
