name: Release Candidate to Staging

on:
  push:
    tags:
      - 'release/v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Maliev.AuthService.sln

    - name: Build
      run: dotnet build Maliev.AuthService.sln --no-restore

    - name: Test
      run: dotnet test Maliev.AuthService.sln --no-build --verbosity normal

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: maliev-website
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        export RELEASE_VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/v,,g')
        docker build -t asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-staging/maliev-authservice:$RELEASE_VERSION -f Maliev.AuthService.Api/Dockerfile .
        docker push asia-southeast1-docker.pkg.dev/maliev-website/maliev-website-artifact-staging/maliev-authservice:$RELEASE_VERSION